// <auto-generated />
using System;
using FinancialAccountService.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinancialAccountService.Migrations
{
    [DbContext(typeof(FinancialAccountDbContext))]
    [Migration("20210804164605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("FinancialAccountService.Database.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Summ")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("FinancialAccountService.Database.BalanceTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OperationTtype")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Summ")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.ToTable("BalanceTransaction");
                });

            modelBuilder.Entity("FinancialAccountService.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FinancialAccountService.Database.BalanceTransaction", b =>
                {
                    b.HasOne("FinancialAccountService.Database.Balance", null)
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("BalanceId");
                });

            modelBuilder.Entity("FinancialAccountService.Database.User", b =>
                {
                    b.HasOne("FinancialAccountService.Database.Balance", "CurrentBalance")
                        .WithMany()
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentBalance");
                });

            modelBuilder.Entity("FinancialAccountService.Database.Balance", b =>
                {
                    b.Navigation("BalanceTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
